
--------------ROLE----------------

---Create Role----
CREATE ROLE ADMIN
CREATE ROLE CUSTOMER 
CREATE ROLE SELLER


-------------GRANT------------

---ADMIN---
GRANT EXECUTE ON [dbo].[sp_DeleteAccount] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_DeleteBill] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_DeleteCategory] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_DeleteContact] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_DeleteDetailOrder] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_DeleteMember] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_DeleteOrder] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_DeleteProduct] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_getAllAccount] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_getAllBill] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_getAllCategory] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_getAllContact] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_getAllMember] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_getAllOrder] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_getAllProduct] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_getAllDetailOrder] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_getOneAccount] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_getOneBill] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_getOneCategory] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_getOneContact] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_getOneDetailOrder] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_getOneMember] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_getOneOrder] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_getOneProduct] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_getProductBySaleID] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_InsertAccount] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_InsertBill] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_InsertCategory] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_InsertContact] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_InsertDetailOrder] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_InsertMember] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_InsertOrder] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_InsertOrderWithDetail] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_InsertProduct] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_UpdateAccount] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_UpdateBill] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_UpdateCategory] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_UpdateContact] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_UpdateDetailOrder] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_UpdateMember] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_UpdateOrder] TO ADMIN WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_UpdateProduct] TO ADMIN WITH GRANT OPTION
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[Account] TO ADMIN WITH GRANT OPTION
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[Bill] TO ADMIN WITH GRANT OPTION
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[Category] TO ADMIN WITH GRANT OPTION
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[Contact] TO ADMIN WITH GRANT OPTION
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[DetailOrder] TO ADMIN WITH GRANT OPTION
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[Member] TO ADMIN WITH GRANT OPTION
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[Order] TO ADMIN WITH GRANT OPTION
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[Product] TO ADMIN WITH GRANT OPTION
GRANT SELECT ON [dbo].[fn_HoaDon] TO ADMIN WITH GRANT OPTION
GRANT SELECT ON [dbo].[fn_ProductAndAmount] TO ADMIN WITH GRANT OPTION
GRANT SELECT ON [dbo].[fn_ProductByCateName] TO ADMIN WITH GRANT OPTION
GRANT SELECT ON [dbo].[fn_ProductBySalerName] TO ADMIN WITH GRANT OPTION
GRANT SELECT ON [dbo].[fn_ProductInRangePrice] TO ADMIN WITH GRANT OPTION
GRANT SELECT ON [dbo].[fn_SearchMaxPriceByCategory] TO ADMIN WITH GRANT OPTION
GRANT SELECT ON [dbo].[fn_SearchProductName] TO ADMIN WITH GRANT OPTION


---SELLER---
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[Product] TO SELLER WITH GRANT OPTION
GRANT SELECT, INSERT, DELETE ON [dbo].[Order] TO SELLER WITH GRANT OPTION
GRANT SELECT, INSERT ON [dbo].[DetailOrder] TO SELLER WITH GRANT OPTION
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[Member] TO SELLER WITH GRANT OPTION
GRANT UPDATE ON [dbo].[Account] TO SELLER WITH GRANT OPTION
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[Bill] TO SELLER WITH GRANT OPTION
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[Category] TO SELLER WITH GRANT OPTION
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[Contact] TO SELLER WITH GRANT OPTION


GRANT SELECT ON [dbo].[fn_HoaDon] TO SELLER WITH GRANT OPTION
GRANT SELECT ON [dbo].[fn_ProductAndAmount] TO SELLER WITH GRANT OPTION
GRANT SELECT ON [dbo].[fn_ProductByCateName] TO SELLER WITH GRANT OPTION
GRANT SELECT ON [dbo].[fn_ProductBySalerName] TO SELLER WITH GRANT OPTION
GRANT SELECT ON [dbo].[fn_ProductInRangePrice] TO SELLER WITH GRANT OPTION
GRANT SELECT ON [dbo].[fn_SearchMaxPriceByCategory] TO SELLER WITH GRANT OPTION
GRANT SELECT ON [dbo].[fn_SearchProductName] TO SELLER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_DeleteBill] TO SELLER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_DeleteCategory] TO SELLER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_DeleteContact] TO SELLER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_DeleteDetailOrder] TO SELLER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_DeleteMember] TO SELLER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_DeleteOrder] TO SELLER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_DeleteProduct] TO SELLER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_getAllCategory] TO SELLER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_getAllContact] TO SELLER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_getAllProduct] TO CUSTOMER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_getOneDetailOrder] TO SELLER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_getOneBill] TO SELLER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_getOneCategory] TO SELLER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_getOneContact] TO SELLER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_getOneDetailOrder] TO SELLER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_getOneMember] TO SELLER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_getOneOrder] TO SELLER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_getOneProduct] TO SELLER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_getProductBySaleID] TO SELLER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_InsertBill] TO SELLER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_InsertCategory] TO SELLER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_InsertContact] TO SELLER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_InsertDetailOrder] TO SELLER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_InsertMember] TO SELLER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_InsertOrder] TO SELLER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_InsertOrderWithDetail] TO SELLER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_InsertProduct] TO SELLER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_UpdateAccount] TO SELLER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_UpdateBill] TO SELLER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_UpdateCategory] TO SELLER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_UpdateContact] TO SELLER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_UpdateMember] TO SELLER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_UpdateProduct] TO SELLER WITH GRANT OPTION


---CUSTOMER---
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[Member] TO CUSTOMER WITH GRANT OPTION
GRANT SELECT, INSERT, UPDATE ON [dbo].[Account] TO CUSTOMER WITH GRANT OPTION
GRANT SELECT, INSERT ON [dbo].[Order] TO CUSTOMER WITH GRANT OPTION
GRANT SELECT, INSERT ON [dbo].[DetailOrder] TO CUSTOMER WITH GRANT OPTION
GRANT SELECT ON [dbo].[fn_HoaDon] TO CUSTOMER WITH GRANT OPTION
GRANT SELECT ON [dbo].[fn_ProductAndAmount] TO CUSTOMER WITH GRANT OPTION
GRANT SELECT ON [dbo].[fn_ProductByCateName] TO CUSTOMER WITH GRANT OPTION
GRANT SELECT ON [dbo].[fn_ProductBySalerName] TO CUSTOMER WITH GRANT OPTION
GRANT SELECT ON [dbo].[fn_ProductInRangePrice] TO CUSTOMER WITH GRANT OPTION
GRANT SELECT ON [dbo].[fn_SearchMaxPriceByCategory] TO CUSTOMER WITH GRANT OPTION
GRANT SELECT ON [dbo].[fn_SearchProductName] TO CUSTOMER WITH GRANT OPTION

GRANT EXECUTE ON [dbo].[sp_DeleteDetailOrder] TO CUSTOMER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_DeleteOrder] TO CUSTOMER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_getAllCategory] TO CUSTOMER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_getAllContact] TO CUSTOMER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_getAllProduct] TO CUSTOMER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_getOneCategory] TO CUSTOMER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_getOneContact] TO CUSTOMER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_getOneDetailOrder] TO CUSTOMER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_getOneOrder] TO CUSTOMER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_getOneProduct] TO CUSTOMER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_InsertAccount] TO CUSTOMER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_InsertOrder] TO CUSTOMER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_InsertOrderWithDetail] TO CUSTOMER WITH GRANT OPTION
GRANT EXECUTE ON [dbo].[sp_UpdateAccount] TO CUSTOMER WITH GRANT OPTION

